company_terms <- c("Unfiltered Tweets" = "NoFilter",
                  "3M" = "3M",
                   "Adidas" = "adidas",
                   "Allianz" = "Allianz",
                   "American Express" = "American Express",
                   "Amgen" = "Amgen",
                  "Apple" = "Apple",
                  "BASF" = "BASF",
                  "Bayer" = "Bayer",
                  "Beiersdorf",
                  "BMW",
                  "Boeing",
                  "Caterpillar",
                  "Chevron",
                  "Cisco",
                  "Coca-Cola",
                  "Continental",
                  "Covestro",
                  "Daimler",
                  "Delivery Hero",
                  "Deutsche Bank",
                  "Deutsche Börse",
                  "Deutsche Post",
                  "Deutsche Telekom",
                  "Deutsche Wohnen",
                  "Dow",
                  "EON",
                  "Fresenius",
                  "Fresenius Medical Care",
                  "Goldman Sachs",
                  "HeidelbergCement",
                  "Henkel",
                  "Home Depot",
                  "Honeywell International",
                  "IBM",
                  "Infineon Teechnologies",
                  "Intel",
                  "Johnson & Johnson" = "JohnsonJohnson",
                  "JPMorgan",
                  "Linde",
                  "McDonald's",
                  "Merck (German)" = "MerckDE",
                  "Merck (American)" = "MerckEN",
                  "Microsoft",
                  "MTU Aero Engines",
                  "Münchener Rück",
                  "NIKE" = "NIKE",
                  "Procter & Gamble = Procter Gamble",
                  "RWE",
                  "Salesforce" = "salesforce",
                  "SAP",
                  "Siements",
                  "Traverlers Companies",
                  "UnitedHealth",
                  "Verizon",
                  "Visa",
                  "Volkswagen",
                  "Vonovia",
                  "Walgreens Boots Alliance",
                  "Walmart",
                  "Walt Disney"
                  )
